### PR TITLE
Add some new features

### PR DESCRIPTION
**Pull request by takaxp**
Hi!

I love this package and tried to add new features. Also I changed some parts in this package to pass the validation of the current MELPA adoption by `checkdoc` and `package-lint-current-buffer`.

Feature 1:
- Supporting to count today's effort within a specific subtree.
- Providing two private variables `org-clock-today--subtree-time` and `org-clock-today--buffer-time`. `org-clock-today--buffer-time` stores the normal count results that the package previously provided. And `org-clock-today--subtree-time` stores the count results limited to the focused subtree.
- Providing a flag to use `org-clock-today--subtree-time` or not.
- Providing a toggle to change the flag as `org-clock-today-toggle-count-subtree`.

Feature 2:
- Supporting to customize displaying format on the mode-line
- Providing custom variable to change the format as `org-clock-today-display-format`
- Providing the default function as `org-clcok-today--display-default`

Any questions and suggestions are welcome!

Best,
Takaaki

### CODE REVIEW

**Comment by mallt** [comment]
@takaxp Thanks a lot! I will try to review this PR during the next couple of days.

**Comment by mallt** [comment]
@takaxp Thanks again for this PR and sorry for the delay! I only have 2 small remarks:

- I would prefer to keep the variable `org-clock-today--string` "public" (I mean with only 1 hyphen instead of 2) because this is the lighter of the minor mode and some people might use this variable in a custom mode line (as I do myself :))
- For the version number I would prefer to set it to 0.0.2 instead of 1.9.9

Thanks!

**Comment by takaxp** [comment]
Hi!

Thank you for reviewing. I agree with you and also make `org-clock-today-subtree-time` and `org-clock-today-buffer-time` public as well because I use them :)
I made some minor changes on docstrings and copyright year.

Best,
Takaaki

**Comment by mallt** [comment]
Thanks a lot @takaxp! Looks great! Would it be possible to squash your commits?

**Comment by takaxp** [comment]
Hi!

In my understanding, the squash would be possible in your side because you can select the merge type. We can see the capability at https://help.github.com/en/articles/merging-a-pull-request. I mean it is possible to squash my commits by selecting "Squash and merge" :)

Or if my understanding is incorrect, could you please instruct me?. I'll do anything for you :)

**Comment by mallt** [comment]
@takaxp I've merged and squashed the commits from the command line. It seems this doesn't trigger an automatic closing of the PR however, so I'll close it manually.

Thanks a lot for your great contributions!

**Comment by takaxp** [comment]
@mallt Many thanks to your quick actions!!

**Pull request closed without merging**
