### PR TITLE
Consider org-clock-report-include-clocking-task when computing total …

### PR DESCRIPTION
**Pull request by ErkiDerLoony**
…minutes

### CODE REVIEW

**Comment by mallt** [comment]
Hi @ErkiDerLoony, I'm not sure I understand your change. Could you perhaps give an example of what you would like to achieve? 

By default the org-clock-today package only shows it's mode line when there are active clocks so it seems a bit strange to me to check the include-clocking-task variable.

Thanks!

**Comment by ErkiDerLoony** [comment]
Hi @mallt,
sorry I did not explain any further. I think there is a bug in the computation of the time displayed in the mode-line: If `org-clock-report-include-clocking-task` is non-nil `(org-clock-sum-today)` already contains the time of the currently clocking task. Thus, in this case if you compute the total clock time of today in `(org-clock-today--total-minutes)` the time of the currently running task is counted twice.
Consider the following example:
```
* Test
:LOGBOOK:
CLOCK: [2019-11-28 Thu 11:00]
CLOCK: [2019-11-28 Thu 10:00]--[2019-11-28 Thu 10:30] =>  0:30
:END:
```
If it is now 11:30 (and `org-clock-report-include-clocking-task` is `t`) the mode-line shows me a today total clock time of 1:30 instead of the 1:00 which I would expect.
If `org-clock-report-include-clocking-task` is `nil` the mode-line displays the correct 1:00.

**Comment by mallt** [comment]
@ErkiDerLoony Ok I see, thank you for the explanation! 

I didn't know about the `org-clock-report-include-clocking-task`variable, but instead of checking it's value I think it would be better if we bind it to `t` so the `org-clock-sum-today` function always takes the clocking task into account. Then we do not need to calculate the open time difference ourselves anymore.

Would you mind changing this PR to force the `org-clock-report-include-clocking-task` to `t` with a let binding around the `org-clock-sum-today` call?

Thanks a lot!

**Comment by ErkiDerLoony** [comment]
You are right, that is a better solution. I updated the pull request.

**Comment by mallt** [comment]
Thanks a lot!

**Pull request merged**
